### ISSUE TITLE
Feature request: (even) more stats, better search/listing

### ISSUE THREAD

**Issue by alexwidua** [Teelevision/zcatch#5]
advanced stats:
- track clan (for web-version)
- track player country flag (for web-version?)
-  track amount your releases (idea: calculate a fairness quotient or something else)
- track rocketjumps to calculate accurate hit/kill ratio/accuracy
- track % of time ingame / in spectator mode (as seen on ddnet srv)

---

regarding the (ingame) search: 
=> /rank player1  :: player NOT found
=> /rank Player1  :+1:

**Comment by Teelevision** [comment]
Tracking players' clan and country is different from saving stats. You can do this externally and I recommend you do it that way for a web version (building and keeping a database with username clan country relations).

Releases could be tracked, but I think it is not a fairness indicator, since one can overuse it.

Counting rocketjumps is planned.

Ingame/spec time could be saved, too, I guess.

The /rank command is case sensitive.

**Comment by alexwidua** [comment]
Forgot about the fact that your TwRequest comes with this feature (flag etc).

Yeah, but for overusing you need to catch someone first; releasing him ain't that bad then I think. but nvm :smile: 

Case sensitive? Why's that?

**Comment by Teelevision** [comment]
Because there can be 2 players, one named 'tee' and the other 'Tee', on the server at the same time. And for the releases: I can track them. I don't see the use in calculating a fairness index, but that doesn't mean there are no other uses.

**Comment by Teelevision** [comment]
As I'm not planning to implement further stats at the moment, I'm closing this issue. If you have additional thoughts about this topic, please open another issue.
