### ISSUE TITLE
2 Password authentication for subadmins

### ISSUE THREAD

**Issue by jxsl13** [Teelevision/zcatch#8]
I'd really like to see a second password, when the subadmin is logged in with his first password to be able to make it less secure, but overall more secure if the admin has bound his first password somewhere, someone who's got his hands on the first one won't possibly have the second one.

moreover the logout command should work without a password or if you type in the password incorrectly, the server would log you out automatically.

**Comment by Teelevision** [comment]
The vanilla server does not log wrong rcon passwords. Are there mods that do so?

Also the password check in the rcon is per line, not per command. So making an exception for the logout command would be ugly. Furthermore entering a wrong password 4 times logs you out.

I introduced the password in the rcon against ip spoofing. So I see it as a temporary solution until that is fixed. It makes the rcon harder to use.

**Comment by Teelevision** [comment]
As there was no further input, I'm not going to add a second password as requested.

**Comment by jxsl13** [comment]
Actually meant to change the anti spoof password in front of every command
of subadmins to something different from the <user>:<password>,  cuz the
later one can be found out with a honey pot server.

**Comment by Teelevision** [comment]
Yes, I understood that. My question was if there are significant server mods that log rcon tries. I do not know any.

The honey pot argument is not thought through. If I made a honey pot, I would let the user log in with any rcon so that he does not notice that he is on the wrong server. And then capture everything he tries to execute, containing the second rcon.
